- set_fact:
    dcsg_path: "/usr/local/bin/dcsg"

- name: Install docker compose to systemd service generator
  get_url:
    url: https://github.com/andreaskoch/dcsg/releases/download/v0.4.0/dcsg_linux_amd64
    dest: "{{ dcsg_path }}"
    owner: vagrant
    group: docker
    mode: '0770'
  become: yes