---

- name: Install Docker SDK for Python
  pip:
    name: docker
  become: yes

- name: Install docker compose
  pip:
    name: docker-compose
  become: yes

- name: create local roles folder
  file:
    path: "/usr/local/etc/docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0770'
  become: yes