---

- name: Install package from repo
  package:
    name: docker
    state: present
  become: yes

- name: Add the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: yes
  become: yes

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    enabled: yes
  become: yes

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
  become: yes