---

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    enabled: yes
  become: yes

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: yes